### ISSUE TITLE
Can't create more than 4294967295 entities

### ISSUE THREAD

**Issue by graphitemaster** [nem0/lent#5]
As good as this framework is (it's a framework because it's quite bloated, maybe need to cleanup some of the interfaces a little), it somehow lacks support for `> 4294967295` entities. I think maybe `lent` needs to consider using a larger integer type. Though one can argue that we should maybe make a lent2 or lent64 so we don't break backwards compatibility with projects using classic lent, any objections?

**Comment by nem0** [comment]
Hi graphitemaster, 

there is a nice trick that allows you to create more than 4294967295 entities. Use 0 as a valid entity and you get 4294967296 possible values, and that's enough for everybody.

XOXO,
Nem0
