### ISSUE TITLE
Imperial Royal Guard uses C++ style comments

### ISSUE THREAD

**Issue by graphitemaster** [nem0/lent#7]
The introduction of the Imperial Royal Guard to fix issue #6 introduces problems for C compilers that do not understand the `//` comments.

**Comment by mtwilliams** [comment]
Personally, I prefer `#ifdef 0` comments because they're more efficient.

**Comment by nem0** [comment]
```#if 0``` are even more

**Comment by ttvd** [comment]
Let's not get derailed from the issue at hand, I can't compile this on my PGI compiler.

**Comment by nem0** [comment]
@ttvd what is the problem? guard is already there

**Comment by nem0** [comment]
since I can't remember which comment is C style and which is C++, I decided for ```#ifdef SOME_SHIT``` style. Fixed via https://github.com/nem0/lent/commit/b7f70280cc69522b7ea81f7c0d78ea935b50e495
XOXO
Nem0

**Comment by ttvd** [comment]
You are the hero we deserve.
