### ISSUE TITLE
You should rewrite this in Rust

### ISSUE THREAD

**Issue by mtwilliams** [nem0/lent#8]
Rust is superior to C in every way. It will make this code more safe. You should rewrite it.

**Comment by nem0** [comment]
Hi mtwilliams,

I like to live dangerously. 
But if some other hipster want to rewrite lent in rust, he can pay me and I will allow him to do it.

XOXO,
Nem0

**Comment by Alan-FGR** [comment]
@nem0 darn you stealing my words!
